import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Leftbar from '../components/leftbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          <aside className='flex-[1]'> <Leftbar/> </aside>
          <main className='flex-[4]'>{children}</main>
        </div>
        </body>
    </html>
  )
}
