version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app/app
      - ./frontend/public:/usr/src/app/public
    restart: always
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      target: dev
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src
    restart: always
    ports:
      - 8000:8000   
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: database
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: chatapp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10  
    volumes:
      - mysql_chatapp:/var/lib/mysql  

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin:4.9.7
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  mysql_chatapp:
