version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    restart: always
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    container_name: backend-api
    build:
      target: dev
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src
    restart: always
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mern-network

  db:
    container_name: database
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: chatapp
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_chatapp:/var/lib/mysql
    networks:
      - mern-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mern-network

volumes:
  mysql_chatapp:

networks:
  mern-network:
      driver: bridge